### ISSUE TITLE
ajax timeout error does not pass error to error callback

### ISSUE THREAD

**Issue by pgilad** [AmpersandJS/ampersand-model#34]
See this:
https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L126

While ampersand-sync passes the following information:
https://github.com/AmpersandJS/ampersand-sync/blob/master/ampersand-sync.js#L102

**Comment by wraithgar** [comment]
This is fixed in v4.0.4.  Thanks for finding this.

**Comment by pgilad** [comment]
:1:
