### ISSUE TITLE
beforeSend is never called

### ISSUE THREAD

**Issue by herkyl** [AmpersandJS/ampersand-model#36]
When defining a beforeSend in the ajaxConfig it never gets called

**Comment by herkyl** [comment]
I noticed when I delegate the model's sync function to ampersand-sync beforeSend gets called

```
Model = require 'ampersand-model'
sync = require 'ampersand-sync'

model = Model.extend

  ajaxConfig:
    beforeSend: ->
      debugger

  sync: ->
    AmpersandSync.apply @, arguments
```

**Comment by adamyonk** [comment]
Getting ampersand-sync to a more recent version fixed this same issue for me. Has to do with AmpersandJS/ampersand-sync#23.
