### ISSUE TITLE
Attributes being marked as "not changed" before persisting to server

### ISSUE THREAD

**Issue by mhuggins** [AmpersandJS/ampersand-model#4]
I have a model with properties as such:

```
var Profile = BaseModel.extend({
  props: {
    firstName: 'string',
    lastName: 'string',
    avatar: 'string'
  }
});
```

My model initialization should denote that all attributes start as `null` or `undefined`:

```
var profile = new Profile();
```

From a React view, I am then updating the avatar to a local file URI (for when user captures photo or selects a photo in the context of a Cordova app), e.g.:

```
function onPhotoChanged: function (uri) {
  this.props.profile.set('avatar', uri);
}
```

Later, when the user clicks the "Save" button, I actually persist to the server:

```
function onSubmit: function (event) {
  this.props.profile.save({
    firstName: this.refs.firstName.value(),
    lastName: this.refs.lastName.value(),
    avatar: this.refs.avatar.value()
  }, {
    success: this.onSuccess.bind(this),
    error: this.onError.bind(this)
  })
}
```

All the attributes are being propagated correctly.  However, because of the `set('avatar', uri)` call in the `onPhotoChanged` handler, my Ampersand model thinks that the avatar value has NOT changed (via `hasChanged()`) even though it has yet to be persisted to the server up until the point that I actually call `save`.  (FWIW, I'm calling `hasChanged` from my `Profile#sync` method prior to persisting, and I can see that all other attributes are properly marked as changed.)  Looking at the `previousAttributes` object shows that it's not considering "avatar" null or undefined, but is instead stating that its initial value is whatever last came back when calling `set('avatar', uri)`.

For example:

```
if (this.profile.hasChanged('avatar')) {
  // Separate handling logic for saving avatar image.
  // This never gets called!
}
```

This seems like a bug to me, is this the expected behavior?

**Comment by HenrikJoreteg** [comment]
Sorry for the delay on this. Several folks have been confused about the meaning of `hasChanged` so I added some documentation to clarify what it means. In the commit referenced above. Essentially, `hasChanged` is only useful inside change handlers, it gets wiped out after the change has finished happening. It has nothing to do with whether the model has been persisted to the server or not. I've tried to clarify that in the docs here: https://github.com/AmpersandJS/ampersand-state/commit/cc0bbc602c3aa7c1615e1041dd4707ae06444657

Thanks!
