### ISSUE TITLE
A collection declared as a prop introduces errors.

### ISSUE THREAD

**Issue by EvanCarroll** [AmpersandJS/ampersand-model#59]
I think if you have a collection and a prop by the same name, a fatal error should be thrown when one tries to override the other. My code only works as a collection..

```js
module.exports = BaseModel.extend({        
  props: {                                 
    clientid: 'number'                     
    // , events: 'object'                     
  }                                        
  , collections: { events: NE } 
```

**Comment by cdaringe** [comment]
@pgilad recently did _just_ this.  https://github.com/AmpersandJS/ampersand-state/pull/192.  looks like the &-model deps just need to be bumped to `ampersand-state@4.6.x+`

**Comment by kamilogorek** [comment]
`ampersand-state` has been bumped, therefore closing this one.
